In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50])
print(a.shape)
print(a.ndim)
print(a.dtype)

(5,)
1
int64


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b.size)
print(b.itemsize)
print(b.size * b.itemsize)
print(b.nbytes)

6
8
48
48


In [4]:
a = np.array([1,2,3], dtype='int16')
print(a.itemsize)

2


In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [6]:
print(a[1,3])

11


In [7]:
print(a[:,3])

[ 4 11]


In [ ]:
print(a[0, 1:6:2]) 

[2 4 6]


In [10]:
a[1,4] = 0
a[1,5] = 0
a[1,6] = 0
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11  0  0  0]]


In [13]:
b = np.array([[[1,2], [3,5]],[[5,6], [7,8] ]])
print(b[1,0,1])

6


In [14]:
a = np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
b = np.full((3,3), 7)
print(b)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [17]:
a = np.random.randint(1,10,size=(2,3))
print(a)

[[7 6 8]
 [7 8 4]]


In [21]:
a = np.ones((5,5))
a[1:4,1:4] = np.zeros((3,3))
a[2,2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
a = np.array([1,2,3])
b = a
b[0] = 99
print(a)

[99  2  3]


In [23]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 99
print(a)

[1 2 3]


In [24]:
a = np.array([[1,2,3],[4,5,6]])
b = a.copy()
b[1,2] = 7
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 7]]


In [26]:
a = np.array([1,2,3,4])
print(a*a)

[ 1  4  9 16]


In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [29]:
a = np.array([0, np.pi/2, np.pi])
print(np.cos(a))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [30]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(np.matmul(a,b))

[[6. 6.]
 [6. 6.]]


In [32]:
a = np.identity(4)
print(np.linalg.det(a))

1.0


In [36]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.max(stats, axis=0))

1
[3 6]
[4 5 6]


In [37]:
print(np.sum(stats, axis=0)) #columnwise sum
print(np.sum(stats, axis=1)) #rowsise sum

[5 7 9]
[ 6 15]


In [41]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((8,1))
print(after)



[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [45]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2]))
print(np.hstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [48]:
data = np.array([[1,50,3],[80,5,90],[10,20,100]])
print(data[data>50])
print(np.any(data>90, axis=0))
print(np.any(data>0, axis=0))

[ 80  90 100]
[False False  True]
[ True  True  True]


In [49]:
print(data[(data>10) & (data < 90)])

[50 80 20]


In [51]:
arr = np.array([10,20,30,40,50,60])
print(arr[[0, 2, 5]])

[10 30 60]
