# Numpy complete guide -> Keith Galli
- **numpy** is a turbo charged version of list.
- lists ka jo allocation hota h wo contiguous nahi hota or agar 1 integer bhi usme store kr rahe h to wo numpy array k comparison me jyada jagah/memory leta hai. Or jyada memory ko read and write karna b comparitively slow hota hai.
- wahi **numpy** me data array me continuous block ki tarah store hota hai isliye or memory b kam leta h to uspe operations bhi faster hote hai.

In [22]:
# numpy library ko import karna
import numpy as np

In [25]:
a = np.array([1,2,3]) #ye ek 1D array hai jise "vector" bhi bolte hai
b = np.array([[9,8,7], [6,5,4]]) #ye ek 2D array jise "matrix" bhi bolte hai

ek array ki 3 importent properties hoti hai:
- a.ndim -> kitne dimensions (1D, 2D, 3D...)
- a.shape -> (rows, columns) -> kaisi shape
- a.dtype -> array k andar kya(int32, float64,etc.)

In [27]:
a.ndim

1

In [28]:
b.shape

(2, 3)

In [29]:
a.dtype

dtype('int64')

**size or itemsize:**
- a.itemsize -> 1 element kitni memory leta hai(in bytes)
- a.size -> total kitne elements hain
- a.nbytes -> total memory (itemsize*size)

In [30]:
a.itemsize

8

In [31]:
a.size

3

In [32]:
a.nbytes

24

## Accessing/Changing elements, rows, columns

kuch kuch list k elements ko access karne jaisa hi bas thoda different syntax

In [38]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [39]:
a[1, 5]    # row 1, column 5 ->13

np.int64(13)

In [40]:
a[0, :]    # pura row 0 (pehli row)

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
a[:, 2]    # pura column 2 (dono rows ka 3rd element)

array([ 3, 10])

In [42]:
a[0, 1:6:2]# row 0 mein, index 1 se 6 tak, 2 ke step mein

array([2, 4, 6])

## Accessing/Changing elements,rows,columns

In [43]:
a[1,5] = 20    # single element change
a[:,2] = [1,2] # entire column replace

**3D Arrays** ke liye Trick outer se inner jao

In [44]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[0,1,1] # ->4 (0th block, 1st row, 1st element)

np.int64(4)

**Initializing Different Types of Arrays**
Ye "shortcut functions" hain jab tumhe khud khud numbers nahi likhne, sirf shape chahiye:
- np.zeros((2,3))
  #sab zero ka 2x3 array
- np.ones((4,2,2))
  #sab ek ka array
- np.full((2,2), 99)
  #ek fix number se bhara array
- np.full_like(a, 4)
  #'a' jaisa shape, par sab 4 se bhara
- np.random.rand(4,2)
  #random decimal numbers (0 to 1)
- np.random.randint(-4,8, size=(3,3))
  #random integers ek range mein
- np.identity(5)
  #identity matrix (linear algebra wala)
- np.repeat(arr, 3, axis=0)
  #array ke elements repeat karna

In [45]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

**Copying Arrays--Sabse badatrap**
- a= np.array([1,2,3])
- b=a     #  GALTI! Yeh sirf reference copy hai
- b[0] = 100
- print(a) # a bhi change ho jayega! [100, 2, 3]

In [46]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


Agar actual alag copy chahiye to :
- b = a.copy() ab b a se independent hai

In [48]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


**Mathematics**
Har operation directly poore array pe element-by-element apply hota hai — koi loop nahi
chahiye:

In [50]:
a = np.array([1,2,3,4])
print(a + 2)
print(a - 2)
print(a * 2)
print(a/2)
print(a**2)
print(np.sin(a))
print(np.cos(a))

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


Do arrays ko bhi add/multiply kar sakte ho (agar shape match kare):

In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

**Linear Algebra**

In [52]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(np.matmul(a,b)) # matrix multiplication (rows x columns rule will be followed)

c = np.identity(3)
print(np.linalg.det(c))      # determinant nikalna

[[6. 6.]
 [6. 6.]]
1.0


Yeh section un logon ke liye zyada relevant hai jo ML/stats mein deep jaana chahte hain — matrix multiply, determinant, inverse, eigenvalues jaisi cheezein np.linalg module mein milti hain. (Yani ye mere liye hi hai)

**Statistics**

In [54]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))        #sabse chota number
print(np.max(stats, axis=1))#har row ka max (axis=1 -> row-wise)
print(np.sum(stats, axis=0))#column-wise sum (axis=0 ->column ke through)

1
[3 6]
[5 7 9]


Axis samajhne ka trick: axis=0 matlab "neeche ki taraf jaao" (column ke through operate karo), axis=1 matlab "side mein jaao" (row ke through operate karo). Yeh confusing lagta hai shuru mein, bas yaad rakho: axis 0 = rows collapse hoti hain, axis 1 = columns collapse hoti hain.

**Reorganizing Arrays**

In [56]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((8,1)) # shape change total elements same rehna chahiye
print(after)

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2]))  # vertically stack karna rows ki tarah upar neeche
print(np.hstack([v1,v2]))  # horizontally -> side by side

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


reshape mein sirf yeh dhyan rakhna hai ki original size aur naya shape ka total product match kare (e.g. 8 elements ko 2x4 ya 4x2 ya 8x1 mein reshape kar sakte ho, but 3x3 mein nahi).

**Load Data from file**

- filedata = np.genfromtxt('data.txt', delimiter=',')
- filedata = filedata.astype('int32')  #type convert karna

Yeh csv/text file se numbers directly array mein load karta hai.

**Boolean Masking & Advanced Indexing**

Yeh video ka sabse "cool" part hai — filtering ka superpower:

- filedata > 50              # yeh True/False ka array deta hai, same shape
- filedata[filedata > 50]    # sirf woh values deta hai jo condition satisfy karti hain

- np.any(filedata > 50, axis=0)    # kya kisi column mein koi value 50 se badi hai?
- np.all(filedata > 50, axis=0)    # kya SAARI values 50 se badi hain?

- ((filedata > 50) & (filedata < 100))   # multiple conditions combine karna

**Advanced indexing** — list ke andar list daal ke multiple specific indices access kar sakte ho:

In [58]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # index 1, 2, aur 8 ke elements ek saath


array([2, 3, 9])

Yeh boolean masking wala concept pandas mein bhi exactly waise hi use hota hai (filtering rows condition ke basis pe) — isliye yeh seekhna direct pandas ke liye foundation hai.

Quick Summary (cheat-sheet style)

- Kaam=================Function
- Array banana=========np.array()
- Shape/dtype dekhna===.shape, .dtype, .ndim
- Zero/one/random======arraynp.zeros(), np.ones(), np.random.rand()
- Copy (safe)==========.copy()
- Math=================+ - * / **, np.sin()
- Matrix multiply======np.matmul()
- Stats================np.min(), np.max(), np.sum(axis=)
- Reshape==============.reshape()
- Stacknp==============.vstack(), np.hstack()
- Filter===============arr[arr > x]

